### ISSUE TITLE
valid_min and valid_max have disappeared

### ISSUE THREAD

**Issue by taylor13** [cmip6dr/variableRanges#2]
@martinjuckes    It appears that valid_min and valid_max are now undefined (but present) for all variables in the data request.  What plans are there to restore them?  

@dnadeau4 @aradhakrishnanGFDL  : CMOR must get these values from the DREQ and no other source.

**Comment by aradhakrishnanGFDL** [comment]
Hi Karl et al, I just wanted to follow-up on this thread on valid_min/max availability. We, at GFDL made use of these values in CMIP5 for QC'ing. We were wondering if it will be made available this time as well. Thanks,

**Comment by martinjuckes** [comment]
reinstated
