### ISSUE TITLE
Variable with a negative value for ok_min_mean_abs

### ISSUE THREAD

**Issue by jypeter** [cmip6dr/variableRanges#4]
@martinjuckes when "playing" with the web interface of the DR, I have just found out a variable that can have a negative min absolute value

http://clipc-services.ceda.ac.uk/dreq/u/d228e0b3-fd45-11e8-9dd4-cb9c85ce3cab.html

`ok_min_mean_abs[i]: -0.0511`

**Comment by martinjuckes** [comment]
Thanks for raising this. There are a number of these inherited from CMIP5. I've now placed a filter to cut these out:
Amon-clwvi: ok_min_mean_abs=-0.03549
Amon-cl: ok_min_mean_abs=-0.04479
Amon-wap: ok_min_mean_abs=-0.005083
Amon-zg: ok_min_mean_abs=-113.4
Amon-hus: ok_min_mean_abs=-0.0003539
Amon-clivi: ok_min_mean_abs=-0.0348
Omon-zostoga: ok_min_mean_abs=-0.0511 
Lmon-mrso: ok_min_mean_abs=-1424
Lmon-mrsos: ok_min_mean_abs=-35.89
Lmon-mrros: ok_min_mean_abs=-5.867e-06
Lmon-mrfso: ok_min_mean_abs=-419
Lmon-mrro: ok_min_mean_abs=-6.668e-06 
LImon-snd: ok_min_mean_abs=-1.961
LImon-snm: ok_min_mean_abs=-2.092e-06 
LImon-snc: ok_min_mean_abs=-29.01
LImon-snw: ok_min_mean_abs=-6025
LImon-sbl: ok_min_mean_abs=-5.521e-05
